# I'd like to run this manually
trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest
  - ubuntu-20.04
- name: adminKey
  displayName: SSH Key for admin user
  type: string
  default: sshkey
- name: addressSpace
  displayName: Address space (also used as subnet) of the TailScale VM vnet
  type: string
  default: 192.168.64.0/24

variables:
- name: one
  value: ${{ parameters.adminKey }}

jobs:
- job: deploy
  displayName: Deploy to Azure
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: |
      Write-Host "You entered ${{ parameters.adminKey }}" ;
      $file = Get-Content ./cloud-init.txt ;
      $file -replace "__REPLACEKEY__","{{ parameters.tailscaleKey }}" ;
      $file -replace "__REPLACEROUTES__","{{ parameters.tailscaleRoutes }}"
      $file | Set-Content ./cloud-init ;
      Get-Content ./cloud-ini
    displayName: Update ARM template parameters file
