# I'd like to run this manually
trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest
  - ubuntu-20.04
- name: tailscaleKey
  displayName: TailScale Pre-auth Key
  type: string
- name: tailscaleRoutes
  displayName: Subnets routed through this TailScale node
  default: 192.168.23.0/24,10.23.0.0/16

jobs:
- job: deploy
  displayName: Deploy to Azure
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - pwsh: |
      $file = Get-Content ./cloud-init.txt ;
      $file -replace "__REPLACEKEY__","{{ parameters.tailscaleKey }}" ;
      $file -replace "__REPLACEROUTES__","{{ parameters.tailscaleRoutes }}"
      $file | Set-Content ./cloud-init ;
      Get-Content ./cloud-ini.txt
    displayName: Update ARM template parameters file
